version: 2
jobs:
  prepare-deploy:
    docker:
      - image: python:3.7-slim
    steps:
      - run: echo hello world
  deploy:
    docker:
      - image: python:3.7-slim
    steps:
      - checkout
